package cron

const (
	N_BOARDS          = 1000
	N_ARTICLES        = 100
	N_ARTICLE_DETAILS = 100

	INVALID_LOAD_GENERAL_ARTICLES_NEXT_IDX_BOARDD = -1

	INVALID_LOAD_GENERAL_ARTICLES_NEXT_IDX_PTT = ""
)
